/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Bedroom.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import * as THREE from 'three';

export function Showroom() {
  const { nodes, materials } = useGLTF('/Bedroom.glb')
  return (
    <group dispose={null} >
      <group position={[-2.419, 2.525, 0.935]}>
        <mesh geometry={nodes.Rectangle2123440922.geometry} material={materials['Material #2147479979']} position={[-0.025, -0.015, 0]} />
      </group>
      <group position={[4.493, 1.149, 1.975]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <group position={[-0.166, -0.066, 0.226]}>
          <mesh geometry={nodes['Obj3d66-1597950-31-752'].geometry} material={nodes['Obj3d66-1597950-31-752'].material} position={[-0.065, -0.187, 0.054]} scale={[1.141, 0.821, 0.989]} />
          <mesh geometry={nodes['Obj3d66-1597950-32-899'].geometry} material={nodes['Obj3d66-1597950-32-899'].material} position={[-0.065, -0.187, 0.054]} scale={[1.141, 0.821, 0.989]} />
          <mesh geometry={nodes['Obj3d66-1597950-33-454'].geometry} material={nodes['Obj3d66-1597950-33-454'].material} position={[-0.071, -0.187, 0.059]} scale={[0.502, 0.597, 0.435]} />
          <mesh geometry={nodes['Obj3d66-1597950-34-293'].geometry} material={nodes['Obj3d66-1597950-34-293'].material} position={[0.042, -0.187, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.829, 0.719, 0.597]} />
          <mesh geometry={nodes['Obj3d66-1597950-35-996'].geometry} material={nodes['Obj3d66-1597950-35-996'].material} position={[0.042, -0.187, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.829, 0.719, 0.597]} />
          <mesh geometry={nodes['Obj3d66-1597950-36-877'].geometry} material={nodes['Obj3d66-1597950-36-877'].material} position={[-0.071, -0.187, 0.059]} scale={[0.357, 0.424, 0.309]} />
          <mesh geometry={nodes['Obj3d66-1597950-8-500'].geometry} material={nodes['Obj3d66-1597950-8-500'].material} position={[-0.069, -0.187, 0.149]} scale={[1.207, 0.869, 1.047]} />
        </group>
        <mesh geometry={nodes.Rectangle2123440953.geometry} material={nodes.Rectangle2123440953.material} position={[0, -0.173, 0]} />
        <mesh geometry={nodes.Rectangle2123440954.geometry} material={nodes.Rectangle2123440954.material} position={[0, -0.11, 0]} />
      </group>
      <group position={[3.527, 1.149, 1.344]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, -1, 1]}>
        <group position={[-0.166, -0.066, 0.226]}>
          <mesh geometry={nodes['Obj3d66-1597950-31-753'].geometry} material={nodes['Obj3d66-1597950-31-753'].material} position={[-0.065, -0.187, 0.054]} scale={[1.141, 0.821, 0.989]} />
          <mesh geometry={nodes['Obj3d66-1597950-32-900'].geometry} material={nodes['Obj3d66-1597950-32-900'].material} position={[-0.065, -0.187, 0.054]} scale={[1.141, 0.821, 0.989]} />
          <mesh geometry={nodes['Obj3d66-1597950-33-455'].geometry} material={nodes['Obj3d66-1597950-33-455'].material} position={[-0.071, -0.187, 0.059]} scale={[0.502, 0.597, 0.435]} />
          <mesh geometry={nodes['Obj3d66-1597950-34-294'].geometry} material={nodes['Obj3d66-1597950-34-294'].material} position={[0.042, -0.187, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.829, 0.719, 0.597]} />
          <mesh geometry={nodes['Obj3d66-1597950-35-997'].geometry} material={nodes['Obj3d66-1597950-35-997'].material} position={[0.042, -0.187, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.829, 0.719, 0.597]} />
          <mesh geometry={nodes['Obj3d66-1597950-36-878'].geometry} material={nodes['Obj3d66-1597950-36-878'].material} position={[-0.071, -0.187, 0.059]} scale={[0.357, 0.424, 0.309]} />
          <mesh geometry={nodes['Obj3d66-1597950-8-501'].geometry} material={nodes['Obj3d66-1597950-8-501'].material} position={[-0.069, -0.187, 0.149]} scale={[1.207, 0.869, 1.047]} />
        </group>
        <mesh geometry={nodes.Rectangle2123440955.geometry} material={nodes.Rectangle2123440955.material} position={[0, -0.173, 0]} />
        <mesh geometry={nodes.Rectangle2123440956.geometry} material={nodes.Rectangle2123440956.material} position={[0, -0.11, 0]} />
      </group>
      <group position={[-2.649, 1.666, 1.898]} rotation={[-Math.PI, 0, 0]} scale={[0.786, -0.786, 0.786]}>
        <group position={[0.027, -0.008, -0.007]}>
          <mesh geometry={nodes['Obj3d66-1536507-75-202'].geometry} material={materials['Material #2147479996']} position={[-0.024, 0, 0.095]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.036, 0.034, 0.036]} />
          <mesh geometry={nodes['Obj3d66-1536507-76-359'].geometry} material={materials['Material #2147479996']} position={[-0.024, 0, 0.095]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.036, 0.034, 0.036]} />
        </group>
        <mesh geometry={nodes['Obj3d66-1536507-74-569'].geometry} material={materials['Material #2147479997']} position={[-0.062, -0.275, 0.244]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.445, -0.454, 1.017]} />
      </group>
      <group position={[-2.628, 1.66, -0.055]} scale={0.786}>
        <mesh geometry={nodes['Obj3d66-1536507-75-201'].geometry} material={materials['Material #2147479996']} position={[-0.024, 0, 0.095]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.036, 0.034, 0.036]} />
        <mesh geometry={nodes['Obj3d66-1536507-76-358'].geometry} material={materials['Material #2147479996']} position={[-0.024, 0, 0.095]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.036, 0.034, 0.036]} />
      </group>
      <group position={[-1.794, 1.765, -1.285]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Rectangle2123440740.geometry} material={materials['Material #2147479985']} position={[-0.341, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440739.geometry} material={materials['Material #2147479985']} position={[-0.309, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440738.geometry} material={materials['Material #2147479985']} position={[-0.277, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440737.geometry} material={materials['Material #2147479985']} position={[-0.245, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440736.geometry} material={materials['Material #2147479985']} position={[-0.213, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440735.geometry} material={materials['Material #2147479985']} position={[0.043, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440734.geometry} material={materials['Material #2147479985']} position={[0.075, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440733.geometry} material={materials['Material #2147479985']} position={[0.107, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440732.geometry} material={materials['Material #2147479985']} position={[0.139, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440731.geometry} material={materials['Material #2147479985']} position={[0.171, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440730.geometry} material={materials['Material #2147479985']} position={[-0.181, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440729.geometry} material={materials['Material #2147479985']} position={[-0.149, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440728.geometry} material={materials['Material #2147479985']} position={[-0.117, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440727.geometry} material={materials['Material #2147479985']} position={[-0.085, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440726.geometry} material={materials['Material #2147479985']} position={[-0.053, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440725.geometry} material={materials['Material #2147479985']} position={[-0.021, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440724.geometry} material={materials['Material #2147479985']} position={[0.011, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440717.geometry} material={materials['Material #2147479985']} position={[0.203, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440716.geometry} material={materials['Material #2147479985']} position={[0.235, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440715.geometry} material={materials['Material #2147479985']} position={[0.267, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440714.geometry} material={materials['Material #2147479985']} position={[0.299, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440713.geometry} material={materials['Material #2147479985']} position={[0.331, -0.005, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
        <mesh geometry={nodes.Rectangle2123440710.geometry} material={materials['Material #2147479985']} position={[0.297, -0.01, -0.39]} rotation={[0, 0, Math.PI]} scale={[1, -1, 1]} />
      </group>
      <PerspectiveCamera makeDefault={false} far={10000} fov={34.516} position={[1.876, 3.73, 6.997]} rotation={[-0.334, 0.402, 0.135]} />
      <mesh geometry={nodes.Rectangle2123440918.geometry} material={materials['Material #2147479983']} position={[-2.564, 0, -0.96]} />
      <mesh geometry={nodes.Rectangle2123440919.geometry} material={materials['Material #2147479983']} position={[3.501, 2.3, 1.238]} />
      <mesh geometry={nodes.Rectangle2123440920.geometry} material={materials['Material #2147479983']} position={[-2.564, 0, 0.935]} />
      <mesh geometry={nodes.Rectangle2123440921.geometry} material={nodes.Rectangle2123440921.material} position={[-2.564, 2.54, 0.935]} />
      <mesh geometry={nodes.Rectangle2123440923.geometry} material={materials['Material #2147479979']} position={[-2.444, 0.45, -0.375]} />
      <mesh geometry={nodes.Rectangle2123440924.geometry} material={materials['Material #2147479979']} position={[-2.444, 0.45, 2.245]} />
      <mesh geometry={nodes.Line029.geometry} material={materials['Material #2147479983']} position={[1.646, 2.6, 0.865]} />
      <mesh geometry={nodes.Rectangle2123440948.geometry} material={nodes.Rectangle2123440948.material} position={[-0.084, 2.85, 0.676]} />
      <mesh geometry={nodes.Rectangle2123440949.geometry} material={materials['Material #2147479986']} position={[-0.064, 2.77, -1.055]} />
      <mesh geometry={nodes.Rectangle2123440950.geometry} material={materials['Material #2147479974']} position={[-2.444, 0.45, 0.935]} />
      <mesh geometry={nodes.Line030.geometry} material={nodes.Line030.material} position={[1.524, -0.05, 0.845]} />
      <mesh geometry={nodes.Line031.geometry} material={materials['Material #2147479993']} position={[1.524, -0.05, 0.845]} />
      <mesh geometry={nodes['Obj3d66-1536507-44-328'].geometry} material={materials['Material #2147479982']} position={[0.023, 0.006, 0.674]} rotation={[0, 0, -Math.PI]} scale={[1.021, -1.208, 0.688]} />
      <mesh geometry={nodes['Obj3d66-1536507-51-704'].geometry} material={materials['Material #2147479973']} position={[-2.322, 0.573, -0.013]} rotation={[1.379, 0, 0]} scale={[0.446, 0.423, 0.485]} />
      <mesh geometry={nodes['Obj3d66-1536507-52-742'].geometry} material={materials['Material #2147479973']} position={[-2.337, 0.597, -0.2]} rotation={[0, 0.044, 0.037]} scale={[0.682, 0.962, 0.831]} />
      <mesh geometry={nodes.Rectangle2123441027.geometry} material={nodes.Rectangle2123441027.material} position={[-2.564, 2.54, 0.935]} />
      <mesh geometry={nodes['Obj3d66-1536507-45-215'].geometry} material={materials['Material #2147479973']} position={[0.514, 0.018, 1.38]} rotation={[0, Math.PI / 9, 0]} scale={[0.783, 0.764, 0.783]} />
      <mesh geometry={nodes['Obj3d66-1536507-74-568'].geometry} material={materials['Material #2147479997']} position={[-2.697, 1.45, 0.157]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.35, -0.357, 0.8]} />
      <mesh geometry={nodes['Obj3d66-1536507-66-922'].geometry} material={materials['Material #2147479980']} position={[-1.645, 0.165, -0.793]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.863, 0.807, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-64-181'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.097, -0.825]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-67-585'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-68-861'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-63-30'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.097, -1.015]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-62-742'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.194, -0.823]} scale={[0.807, 0.936, 0.863]} />
      <mesh geometry={nodes['Obj3d66-1536507-61-56'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-60-471'].geometry} material={materials['Material #2147479985']} position={[-1.725, 0.301, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-65-73'].geometry} material={materials['Material #2147479985']} position={[-1.606, 0.375, -1.202]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes.glass001.geometry} material={nodes.glass001.material} position={[-2.864, 1.495, 0.935]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, -1, 1]} >
             <meshPhysicalMaterial
            transmission={0.95}           // Fully transparent (PBR way)
            thickness={0.1}            // Thickness of glass for refraction
            roughness={0.1}               // Perfectly smooth
            metalness={0}               // Not metallic
            clearcoat={1}               // Extra shine
            clearcoatRoughness={1}
            ior={1}                    // Glass refraction index
            attenuationDistance={5}      // How far light travels before fading
            attenuationColor={"#ffffff"} // No tint
            envMapIntensity={1}          // Reflections from environment
            color={"#ffffff"}            // No tint
            transparent={true}           // Must be true for transmission to work
            side={THREE.DoubleSide}      // Glass visible from both sides
          />
            </mesh>
      <mesh geometry={nodes.wnd003.geometry} material={nodes.wnd003.material} position={[-2.864, 1.495, 0.935]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, -1, 1]} />
      <mesh geometry={nodes['Obj3d66-1536507-221-75'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.301, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-222-871'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-223-174'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.194, -0.823]} scale={[0.807, 0.936, 0.863]} />
      <mesh geometry={nodes['Obj3d66-1536507-224-130'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.097, -1.015]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-225-267'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.097, -0.825]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-226-214'].geometry} material={materials['Material #2147479985']} position={[1.541, 0.375, -1.202]} rotation={[Math.PI / 2, 0, 0]} scale={[0.807, 0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-227-532'].geometry} material={materials['Material #2147479980']} position={[1.502, 0.165, -0.793]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.863, 0.807, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-228-278'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes['Obj3d66-1536507-229-53'].geometry} material={materials['Material #2147479985']} position={[1.422, 0.211, -1.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.807, -0.863, 0.936]} />
      <mesh geometry={nodes.Line024.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, -0.935]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line025.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, -0.515]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Rectangle2123440933.geometry} material={nodes.Rectangle2123440933.material} position={[2.036, 0.977, -0.831]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Rectangle2123440931.geometry} material={nodes.Rectangle2123440931.material} position={[2.036, 0.977, 0.855]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line021.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, 1.171]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line022.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, -0.092]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line023.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, 0.328]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Rectangle2123440932.geometry} material={nodes.Rectangle2123440932.material} position={[2.036, 0.977, 0.012]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line020.geometry} material={materials['Material #2147479985']} position={[2.036, 1.072, 0.751]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line017.geometry} material={materials['Material #2147479985']} position={[2.616, 1.34, 1.305]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Rectangle2123440930.geometry} material={materials['Material #2147479985']} position={[2.616, 0.04, 0.025]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line018.geometry} material={materials['Material #2147479985']} position={[2.616, 1.34, -1.235]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Line019.geometry} material={materials['Material #2147479985']} position={[2.616, 2.6, 0.025]} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Box001.geometry} material={materials['Material #2147479995']} position={[-8.387, -2.364, -2.939]} rotation={[-3.132, 0, 0]} />
      <mesh geometry={nodes.Rectangle2123440929.geometry} material={materials['Material #2147479978']} position={[-0.064, 0.465, -1.295]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle2123440928.geometry} material={materials['Material #2147479985']} position={[1.593, 1.765, -1.295]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle2123440925.geometry} material={materials['Material #2147479985']} position={[-1.011, 1.765, -1.295]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle2123440926.geometry} material={materials['Material #2147479985']} position={[-0.143, 1.765, -1.295]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle2123440927.geometry} material={materials['Material #2147479985']} position={[0.725, 1.765, -1.295]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Bedroom.glb')
export default Showroom;